server:
  port: 8081
spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: prod
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    refresh:
      enabled: true
